#!/bin/bash
# config_env.sh
# Author: Aaron Luna
# Website: alunablog.com
#
# Script Assumes:
#   * Script is called as sudo or root
#   * Six arguments are passed in:
#       1 The name of the MySQL wordpress database
#       2 MySQL username with access to wordpress database
#       3 The MySQL user's password
#       4 The MySQL server's host
#       5 The servername of the wordpress host (i.e., example.com)
#       6 Filepath of the salts_pre file generated by the WP-CLI
#
# Actions Performed:
#   * Parses salts from salts_pre file, creating salts_post file
#   * Populates .env file with wordpress config values
##########################################################################
##########################################################################

# Input validation
if [ $# -eq 0 ]; then
  echo "No arguments supplied"
  exit 1
elif [ $# -lt 6 ]; then
  echo "${#} arguments supplied, 6 are required"
  exit 1
elif [ $# -gt 6 ]; then
  echo "${#} arguments supplied, 6 are required"
  exit 1
fi

# Script Arguments: 
WP_DB_NAME=$1
WP_DB_USER_NAME=$2
WP_DB_USER_TEMP_PASSWORD=$3
WP_DB_HOST=$4
WP_HOST=$5
salts_pre=$6

# Begin script execution
touch salts_post
while IFS= read -r line
do
  echo ${line:28:64} >> salts_post
done <"$salts_pre"

salt1=$(sed '1q;d' salts_post)
salt2=$(sed '2q;d' salts_post)
salt3=$(sed '3q;d' salts_post)
salt4=$(sed '4q;d' salts_post)
salt5=$(sed '5q;d' salts_post)
salt6=$(sed '6q;d' salts_post)
salt7=$(sed '7q;d' salts_post)
salt8=$(sed '8q;d' salts_post)

rm .env
echo "DB_NAME=${WP_DB_NAME}" >> .env
echo "DB_USER=${WP_DB_USER_NAME}" >> .env
echo "DB_PASSWORD=${WP_DB_USER_TEMP_PASSWORD}" >> .env
echo -e "\n" >> .env

echo "# Optional variables" >> .env

if [ "$WP_DB_HOST" != "localhost" ]; then
  echo "DB_HOST=${WP_DB_HOST}" >> .env
else
  echo "# DB_HOST=localhost" >> .env
fi

echo "# DB_PREFIX=wp_" >> .env
echo -e "\n" >> .env

echo "WP_ENV=development" >> .env
echo "WP_HOME=http://${WP_HOST}" >> .env
echo "WP_SITEURL=http://${WP_HOST}/wp" >> .env
echo -e "\n" >> .env

echo "# Generate your keys here: https://roots.io/salts.html" >> .env
echo "AUTH_KEY='${salt1}'" >> .env
echo "SECURE_AUTH_KEY='${salt2}'" >> .env
echo "LOGGED_IN_KEY='${salt3}'" >> .env
echo "NONCE_KEY='${salt4}'" >> .env
echo "AUTH_SALT='${salt5}'" >> .env
echo "SECURE_AUTH_SALT='${salt6}'" >> .env
echo "LOGGED_IN_SALT='${salt7}'" >> .env
echo "NONCE_SALT='${salt8}'" >> .env